name: version
on:
  push:
    branches:
      - main
env:
  REPO: i506dk/ssad

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: semantic_versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      - name: tag-version
        uses: juliansangillo/tag-version@v1.5
        with:
          production-branch: main
          test-branch: main
          dev-branch: main
          
      # Create version tag
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.semantic_versioning.outputs }}
          #message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
