name: version
on:
  push:
    branches:
      - main
env:
  REPO: i506dk/ssad

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0
          
      # Create semantic version
      - name: Semantic Versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}" #-prerelease${increment}"
          
      # Create version tag
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          #version: ${{ steps.versioning.version }}
          version: "${steps.versioning.major}.${steps.versioning.minor}.${steps.versioning.patch}"
          #message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      #- name: Create Release With Tag
      #  id: create_tag
        # You may pin to the exact commit or the version.
        # uses: badico-cloud-hub/create-release-with-tag@2224950683aba50c131efafce2d251d74a8dad75
      #  uses: badico-cloud-hub/create-release-with-tag@v1
      #  with:
          # Branch for release in repository
          #branch: # optional, default is ${{github.event.repository.default_branch}}
          # Tag name for release
      #    tag: ${{ steps.versioning.version }}
          # Just set tag
          #just-tag: # optional
          # Token with credentials for repository
      #    gh-token: ${{ secrets.GITHUB_TOKEN }}
          # Tag name for append in commit
          #append-tag: # optional
          # Set append-tag name to uppercase
          #upper: # optional
