name: version
on:
  push:
    branches:
      - main
env:
  REPO: i506dk/ssad

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0
          
      # Create semantic version
      - name: Semantic Versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}" #-prerelease${increment}"
          
      # Create version tag
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.versioning.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
